# Generated by Django 4.2.5 on 2023-11-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('visual', models.CharField(max_length=50)),
                ('otimizado', models.CharField(max_length=50)),
                ('intuitividade', models.CharField(max_length=50)),
                ('proposta', models.CharField(max_length=50)),
                ('perfil', models.CharField(max_length=50)),
                ('moradores', models.CharField(max_length=50)),
                ('gasto', models.CharField(max_length=50)),
                ('proposta_energeazy', models.CharField(max_length=50)),
                ('intuitividade_energeazy', models.CharField(max_length=50)),
                ('otimizado_energeazy', models.CharField(max_length=50)),
                ('gosto_visual_energeazy', models.CharField(max_length=50)),
            ],
        ),
    ]
