# Generated by Django 4.2.5 on 2023-09-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_dispositivos_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivos',
            name='icone',
            field=models.ImageField(upload_to='icones'),
        ),
    ]
